name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t mon-portfolio .

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_KEY }}
          source: "./"
          target: "/home/pi/portfolio"

      - name: SSH & Run container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_KEY }}
          script: |
            cd portfolio
            docker build -t mon-portfolio .
            docker stop mon-portfolio || true && docker rm mon-portfolio || true
            docker run -d -p 80:3000 --name mon-portfolio mon-portfolio
